// Small host harness: exercises the real extension message handlers without an installed editor.
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function host(initial,configInitial={},inspectLayers={}){
 const store=new Map(),docs=new Map(),panels=[],errors=[],commands=new Map();let nextInput,inputQueue=[],nextPick=0;
 const configStore=new Map(Object.entries(configInitial));
 const inspectStore=new Map();
 for(const [key,value]of Object.entries(inspectLayers)){
  if(key==='workspaceLocaleOrder')inspectStore.set(key,{workspaceValue:value,workspaceFolderValue:value});
  else if(key==='userLocaleOrder')inspectStore.set(key,{globalValue:value});
 }
 const uri=p=>({path:p,toString(){return 'file://'+p;}});
 for(const [name,text]of Object.entries(initial))docs.set(name,{uri:uri('/bundles/'+name),text,getText(){return this.text;},positionAt(n){return n;},version:1,isDirty:false,isClosed:false,languageId:'properties',lineCount:text.split('\n').length,async save(){return true;}});
 const disposable={dispose(){}};
 const api={Uri:{joinPath:(u,...parts)=>uri(path.posix.join(u.path,...parts))},FileType:{File:1},ViewColumn:{Active:1},ConfigurationTarget:{WorkspaceFolder:1},Range:class{constructor(a,b){this.start=a;this.end=b;}},RelativePattern:class{},WorkspaceEdit:class{constructor(){this.edits=[];}replace(uri,range,text){this.edits.push({uri,range,text});}},
 env:{clipboard:{async writeText(t){api.copied=t;}}},commands:{registerCommand(k,cb){commands.set(k,cb);return disposable;},async executeCommand(name,...args){return commands.get(name)?.(...args);}},
 window:{visibleTextEditors:[],createOutputChannel(){return {appendLine(){},show(){}};},async showInputBox(){return inputQueue.length?inputQueue.shift():nextInput;},async showQuickPick(items){return items[nextPick]??items[0];},async showWarningMessage(){return 'Delete';},async showErrorMessage(e){errors.push(typeof e==='string'?e:e?.message||e);return undefined;},createWebviewPanel(){const panel={webview:{messages:[],cspSource:'http://127.0.0.1:4179',asWebviewUri:u=>'http://127.0.0.1:4179/'+path.basename(u.path),async postMessage(m){this.messages.push(JSON.parse(JSON.stringify(m)));},onDidReceiveMessage(cb){this.receive=cb;return disposable;}},reveal(){this.revealed=true;},onDidDispose(cb){this.close=cb;}};panels.push(panel);return panel;}},
 workspace:{workspaceFolders:[{uri:uri('/bundles'),name:'bundles',index:0}],getWorkspaceFolder:()=>({uri:uri('/bundles'),name:'bundles',index:0}),fs:{async readDirectory(){return [...docs.keys()].map(n=>[n,1]);},async writeFile(u,content){const name=path.basename(u.path);const bytes=content instanceof Uint8Array?content:Buffer.from(content);docs.set(name,{uri:uri('/bundles/'+name),text:Buffer.from(bytes).toString('utf8'),getText(){return this.text;},positionAt(n){return n;},async save(){return true;}});}},async openTextDocument(u){return docs.get(path.basename(u.path));},getConfiguration(){const api={get:(k,d)=>configStore.has(k)?configStore.get(k):d,inspect:k=>inspectStore.get(k)??{workspaceValue:configStore.get(k),workspaceFolderValue:configStore.get(k),globalValue:configStore.get(k)},async update(k,v){configStore.set(k,JSON.parse(JSON.stringify(v)));if(k==='workspaceLocaleOrder')inspectStore.set(k,{workspaceValue:v,workspaceFolderValue:v});if(k==='userLocaleOrder')inspectStore.set(k,{globalValue:v});}};return api;},ConfigurationTarget:{Global:1,Workspace:2,WorkspaceFolder:3},createFileSystemWatcher(){return {onDidCreate(){},onDidDelete(){},onDidChange(){},dispose(){}};},onDidChangeTextDocument(){return disposable;},onDidChangeConfiguration(){return disposable;},async applyEdit(e){for(const x of e.edits)docs.get(path.basename(x.uri.path)).text=x.text;return true;}}};
 const context={subscriptions:[],extensionUri:uri('/extension'),workspaceState:{get:k=>store.get(k),async update(k,v){if(v===undefined)store.delete(k);else store.set(k,JSON.parse(JSON.stringify(v)));}}};
 function loadWithVscode(file){const mod={exports:{}};vm.runInNewContext(fs.readFileSync(file,'utf8'),{require:n=>n==='vscode'?api:require(n),module:mod,exports:mod.exports,console,Uint8Array,TextEncoder});return mod.exports;}
 const applyDocument=loadWithVscode(path.join(__dirname,'../src/applyDocument.js'));
 const logMod=loadWithVscode(path.join(__dirname,'../src/log.js'));
 const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/extension.js'),'utf8'),{require:n=>n==='vscode'?api:n==='./properties'?require('../src/properties'):n==='./applyDocument'?applyDocument:n==='./log'?logMod:require(n),module,console,Uint8Array,TextEncoder,crypto:require('node:crypto')});module.exports.activate(context);
 return {panels,docs,errors,store,configStore,inspectStore,api,setInput:v=>nextInput=v,setInputs:(...v)=>{inputQueue=[...v];},setPick:i=>{nextPick=i;},async create(folder){await commands.get('bundleBridge.createBundle')(uri(folder||'/bundles'));},async open(name){await commands.get('bundleBridge.open')(uri('/bundles/'+name));return panels.at(-1);},async send(panel,m){panel.webview.receive(m);for(let i=0;i<24;i++)await new Promise(r=>setImmediate(r));},state:p=>p.webview.messages.filter(m=>m.type==='state').at(-1),notice:p=>p.webview.messages.filter(m=>m.type==='notice').at(-1)};
}
module.exports={host};
