'use strict';
const defaults = {unicodeEscape:true, uppercaseHex:true, delimiter:'=', spacesAroundDelimiter:true, alignment:'none', sortKeys:false, groupKeys:false, groupSeparator:'.', groupDepth:1, blankLinesBetweenGroups:1, wrapColumn:0, wrapIndent:8, wrapAlign:false, wrapAfterNewline:false, valueNewline:'preserve', lineEnding:'preserve', keepEmptyValues:true, generatedHeader:false};
function decode(s) {
  return s.replace(/\\(u[0-9a-fA-F]{4}|u|[\s\S])/g, (_, c) => {
    if(c === 'u') throw new Error('Malformed Unicode escape. Expected \\u followed by four hexadecimal digits.');
    return c[0] === 'u' ? String.fromCharCode(parseInt(c.slice(1),16)) : ({n:'\n',r:'\r',t:'\t',f:'\f'}[c] ?? c);
  });
}
function parse(text) {
  const lines = text.replace(/^\uFEFF/,'').split(/\r\n|\n|\r/); const entries=[]; let comments=[];
  if(lines.at(-1)==='') lines.pop();
  for(let i=0;i<lines.length;i++) {
    let line=lines[i];
    if(/^[ \t\f]*[#!]/.test(line) || /^[ \t\f]*$/.test(line)) {comments.push(line);continue;}
    while((line.match(/\\+$/)?.[0].length ?? 0)%2 === 1) {line=line.slice(0,-1); if(++i>=lines.length) break; line+=lines[i].replace(/^[ \t\f]+/,'');}
    line=line.replace(/^[ \t\f]+/,''); let end=0;
    for(;end<line.length;end++){if(line[end]==='\\'){end++;continue;} if(/[=: \t\f]/.test(line[end]))break;}
    let start=end; while(/[ \t\f]/.test(line[start]??'\0'))start++;
    if(line[start]==='='||line[start]===':')start++;
    while(/[ \t\f]/.test(line[start]??'\0'))start++;
    entries.push({key:decode(line.slice(0,end)),value:decode(line.slice(start)),comments}); comments=[];
  }
  const header=entries.length?entries[0].comments:[];if(entries.length)entries[0].comments=[];
  return {entries, header, trailing:comments, eol:text.includes('\r\n')?'\r\n':text.includes('\r')?'\r':'\n', bom:text.startsWith('\uFEFF')};
}
function encode(s,key,o) {
  let out='';
  for(let i=0;i<s.length;i++) {const c=s[i], n=s.charCodeAt(i);
    if(c==='\\')out+='\\\\';
    else if('\n\r\t\f'.includes(c))out+='\\'+({'\n':'n','\r':'r','\t':'t','\f':'f'}[c]);
    else if((key && ' =:#!'.includes(c)) || (!key && i===0 && c===' '))out+='\\'+c;
    else if(n<32 || (o.unicodeEscape && n>126)) {let h=n.toString(16).padStart(4,'0');out+='\\u'+(o.uppercaseHex?h.toUpperCase():h);}
    else out+=c;
  } return out;
}
function format(model, options={}) {
  const o={...defaults,...options}; const eol=({lf:'\n',crlf:'\r\n',cr:'\r'}[o.lineEnding]||model.eol);
  let rows=model.entries.filter(e=>o.keepEmptyValues||e.value!=='').map(e=>({...e}));
  const group=k=>k.split(o.groupSeparator||'.').slice(0,Math.max(1,o.groupDepth)).join(o.groupSeparator||'.');
  if(o.sortKeys||o.groupKeys)rows.sort((a,b)=>a.key<b.key?-1:a.key>b.key?1:0);
  const encoded=rows.map(e=>encode(e.key,true,o)); const widths=new Map();
  rows.forEach((e,i)=>{const g=o.alignment==='group'?group(e.key):'';widths.set(g,Math.max(widths.get(g)||0,encoded[i].length));});
  const marker='# Generated by BundleBridge';
  const header=model.header||[];
  const result=[]; if(o.generatedHeader && !header.includes(marker) && !model.entries.some(e=>e.comments.includes(marker)) && !model.trailing.includes(marker))result.push(marker);
  result.push(...header);let previous;
  rows.forEach((e,i)=>{
    const g=group(e.key);if(o.groupKeys && previous!==undefined && previous!==g)result.push(...Array(o.blankLinesBetweenGroups).fill(''));previous=g;
    result.push(...e.comments.filter((c)=>!o.groupKeys||c.trim()!==''));
    const width=o.alignment==='none'?encoded[i].length:widths.get(o.alignment==='group'?g:'');
    const space=o.spacesAroundDelimiter?' ':''; const prefix=encoded[i].padEnd(width)+space+o.delimiter+space;
    let v=e.value;if(o.valueNewline!=='preserve')v=v.replace(/\r\n|\r|\n/g,({lf:'\n',crlf:'\r\n',cr:'\r'}[o.valueNewline]));
    const tokens=encode(v,false,o).match(/\\u[0-9a-fA-F]{4}|\\[\s\S]|[\s\S]/gu)||[];
    let line=prefix; const indent=' '.repeat(o.wrapAlign?prefix.length:o.wrapIndent);
    tokens.forEach((token,j)=>{
      if(o.wrapColumn>0 && line.length+token.length>o.wrapColumn-1 && line.length>(line===prefix?prefix.length:indent.length)){result.push(line+'\\');line=indent;}
      // Leading whitespace on a continuation line must be escaped to survive Java's whitespace trimming.
      if(line===indent && token===' ')token='\\ ';
      line+=token;
      if(o.wrapAfterNewline && (token==='\\n'||token==='\\r') && j<tokens.length-1){result.push(line+'\\');line=indent;}
    }); result.push(line);
  });
  result.push(...model.trailing); return (model.bom?'\uFEFF':'')+result.join(eol)+(result.length?eol:'');
}
function bundleName(filename) {
  if(!filename.endsWith('.properties'))return null;
  const stem=filename.slice(0,-11);
  const m=stem.match(/^(.*?)_([a-z]{2,3}(?:_[A-Z][a-z]{3})?(?:_(?:[A-Z]{2}|[0-9]{3}))?(?:_[A-Za-z0-9]+)*)$/);
  return m?{base:m[1],locale:m[2]}:{base:stem,locale:''};
}
function bundleFileName(base,locale){return locale?`${base}_${locale}.properties`:`${base}.properties`;}
function normalizeBundleBase(input){let s=input.trim();if(s.endsWith('.properties'))s=s.slice(0,-11);return s;}
function validateBundleBase(input){
  const base=normalizeBundleBase(input);
  if(!base)return 'Enter a bundle name';
  if(/[/\\:]/.test(base))return 'Name cannot contain path separators';
  const parsed=bundleName(base+'.properties');
  if(!parsed)return 'Invalid bundle name';
  if(parsed.locale)return 'Use the bundle base name only, without a locale suffix';
  if(parsed.base!==base)return 'Invalid bundle name';
  return null;
}
function folderLocales(filenames){
  const locales=new Set();
  for(const filename of filenames){const n=bundleName(filename);if(n)locales.add(n.locale);}
  return [...locales].sort((a,b)=>a.localeCompare(b));
}
function buildLocaleTag({language,script,region,variant}){
  const lang=language?.trim();if(!lang)return '';
  const parts=[lang.toLowerCase()];
  if(script?.trim()){const s=script.trim();parts.push(s.charAt(0).toUpperCase()+s.slice(1).toLowerCase());}
  if(region?.trim()){const r=region.trim();parts.push(/^\d{3}$/.test(r)?r:r.toUpperCase());}
  if(variant?.trim())parts.push(variant.trim());
  return parts.join('_');
}
function localeTagError({language,script,region,variant}){
  const lang=language?.trim(),scr=script?.trim(),reg=region?.trim(),varr=variant?.trim();
  if(!lang){
    if(scr||reg||varr)return 'Language is required when script, region, or variant is set';
    return null;
  }
  if(!/^[a-z]{2,3}$/i.test(lang))return 'Language must be a 2–3 letter ISO 639 code';
  if(scr&&!/^[a-z]{4}$/i.test(scr))return 'Script must be a 4-letter ISO 15924 code (e.g. Hant)';
  if(reg&&!/^([A-Za-z]{2}|\d{3})$/.test(reg))return 'Region must be a 2-letter country code or 3-digit UN M.49 code';
  if(varr&&!/^[A-Za-z0-9]+$/.test(varr))return 'Variant contains invalid characters';
  const tag=buildLocaleTag({language,script,region,variant});
  const parsed=bundleName(`Probe_${tag}.properties`);
  if(!parsed||parsed.locale!==tag)return 'This locale tag is not supported for property file names';
  return null;
}
function normalizeLocaleOrder(value){
  return Array.isArray(value)?value.filter(v=>typeof v==='string'):[];
}
function appendMissingLocales(configuredOrder,detectedLocales){
  const merged=normalizeLocaleOrder(configuredOrder);
  for(const locale of [...new Set(detectedLocales)].sort((a,b)=>a.localeCompare(b)))if(!merged.includes(locale))merged.push(locale);
  return merged;
}
function mergeLocaleOrder(detectedLocales,configuredOrder){
  return appendMissingLocales(configuredOrder,detectedLocales);
}
function localeOrderAppended(before,after){
  const a=normalizeLocaleOrder(before),b=normalizeLocaleOrder(after);
  if(b.length<=a.length)return false;
  for(let i=0;i<a.length;i++)if(a[i]!==b[i])return false;
  return true;
}
function sortFilesByLocaleOrder(items,localeOrder,localeOf){
  const order=Array.isArray(localeOrder)&&localeOrder.length?localeOrder:null;
  const sorted=[...items];
  if(!order)return sorted.sort((a,b)=>localeOf(a).localeCompare(localeOf(b)));
  const rank=new Map(order.map((locale,i)=>[locale,i]));
  return sorted.sort((a,b)=>{
    const la=localeOf(a),lb=localeOf(b);
    const ra=rank.has(la)?rank.get(la):Number.MAX_SAFE_INTEGER;
    const rb=rank.has(lb)?rank.get(lb):Number.MAX_SAFE_INTEGER;
    if(ra!==rb)return ra-rb;
    return la.localeCompare(lb);
  });
}
function values(model){return Object.fromEntries(model.entries.map(e=>[e.key,e.value]));}
module.exports={defaults,parse,format,bundleName,bundleFileName,normalizeBundleBase,validateBundleBase,folderLocales,buildLocaleTag,localeTagError,normalizeLocaleOrder,appendMissingLocales,mergeLocaleOrder,localeOrderAppended,sortFilesByLocaleOrder,values};
